### ISSUE TITLE
Rename naw

### ISSUE THREAD

**Issue by devfemibadmus** [AbdulConsole/ImageColorPicker#1]
ImageColorPicker as how rename to AbdulConsole na since this is ur website

**Comment by AbdulConsole** [comment]
Yes, thanks man but will it affect my cname record ?

**Comment by devfemibadmus** [comment]
> Yes, thanks man but will it affect my cname record ?

hosted on github??

**Comment by devfemibadmus** [comment]
seen, it wont rename it, the cname its in the repo settings

**Comment by AbdulConsole** [comment]
> > Yes, thanks man but will it affect my cname record ?
> 
> hosted on github??

Yes
